//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelationshipAnalysis {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RelationshipAnalysis.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string InvalidPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordMessage", resourceCulture);
            }
        }

        public static string InvalidClauseInSourceCategory {
            get {
                return ResourceManager.GetString("InvalidClauseInSourceCategory", resourceCulture);
            }
        }
        public static string InvalidClauseInDestinationCategory {
            get {
                return ResourceManager.GetString("InvalidClauseInDestinationCategory", resourceCulture);
            }
        }
        public static string InvalidClauseInEdgeCategory {
            get {
                return ResourceManager.GetString("InvalidClauseInEdgeCategory", resourceCulture);
            }
        }

        public static string SuccessfulLogoutMessage {
            get {
                return ResourceManager.GetString("SuccessfulLogoutMessage", resourceCulture);
            }
        }

        public static string UserNotFoundMessage {
            get {
                return ResourceManager.GetString("UserNotFoundMessage", resourceCulture);
            }
        }
        
        public static string WrongOldPasswordMessage {
            get {
                return ResourceManager.GetString("WrongOldPasswordMessage", resourceCulture);
            }
        }
        
        
        public static string NoFileUploadedMessage {
            get {
                return ResourceManager.GetString("NoFileUploadedMessage", resourceCulture);
            }
        }
        public static string SuccessfulNodeAdditionMessage {
            get {
                return ResourceManager.GetString("SuccessfulNodeAdditionMessage", resourceCulture);
            }
        }
        
        public static string TwoSameHeadersMessage {
            get {
                return ResourceManager.GetString("TwoSameHeadersMessage", resourceCulture);
            }
        }
        public static string InvalidNodeCategory {
            get {
                return ResourceManager.GetString("InvalidNodeCategory", resourceCulture);
            }
        }
        public static string InvalidHeaderAttribute {
            get {
                return ResourceManager.GetString("InvalidHeaderAttribute", resourceCulture);
            }
        }
        public static string FailedAddRecordsMessage {
            get {
                return ResourceManager.GetString("FailedAddRecordsMessage", resourceCulture);
            }
        }
        public static string ValidFileMessage {
            get {
                return ResourceManager.GetString("ValidFileMessage", resourceCulture);
            }
        }

        public static string OldPasswordRequired {
            get {
                return ResourceManager.GetString("OldPasswordRequired", resourceCulture);
            }
        }
        
        public static string NewPasswordRequired {
            get {
                return ResourceManager.GetString("NewPasswordRequired", resourceCulture);
            }
        }
        
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        public static string SuccessfulUpdateUserMessage {
            get {
                return ResourceManager.GetString("SuccessfulUpdateUserMessage", resourceCulture);
            }
        }
        
        public static string SuccessfulDeleteUserMessage {
            get {
                return ResourceManager.GetString("SuccessfulDeleteUserMessage", resourceCulture);
            }
        }
        
        public static string UsernameExistsMessage {
            get {
                return ResourceManager.GetString("UsernameExistsMessage", resourceCulture);
            }
        }
        
        public static string EmailExistsMessage {
            get {
                return ResourceManager.GetString("EmailExistsMessage", resourceCulture);
            }
        }
        
        public static string SucceddfulCreateUser {
            get {
                return ResourceManager.GetString("SucceddfulCreateUser", resourceCulture);
            }
        }
        
        public static string EmptyRolesMessage {
            get {
                return ResourceManager.GetString("EmptyRolesMessage", resourceCulture);
            }
        }
        
        public static string InvalidRolesListMessage {
            get {
                return ResourceManager.GetString("InvalidRolesListMessage", resourceCulture);
            }
        }
        
        public static string SuccessfulUpdateRolesMessage {
            get {
                return ResourceManager.GetString("SuccessfulUpdateRolesMessage", resourceCulture);
            }
        }
        
        public static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        public static string SuccessfulLoginMessage {
            get {
                return ResourceManager.GetString("SuccessfulLoginMessage", resourceCulture);
            }
        }
        public static string DeleteAccountAccessErrorMessage {
            get {
                return ResourceManager.GetString("DeleteAccountAccessErrorMessage", resourceCulture);
            }
        }
        
        public static string NullDtoErrorMessage {
            get {
                return ResourceManager.GetString("NullDtoErrorMessage", resourceCulture);
            }
        }
        
        public static string NotUniqueCategoryNameErrorMessage {
            get {
                return ResourceManager.GetString("NotUniqueCategoryNameErrorMessage", resourceCulture);
            }
        }
        
        public static string SuccessfulCreateCategory {
            get {
                return ResourceManager.GetString("SuccessfulCreateCategory", resourceCulture);
            }
        }
        
        
        public static string SuccessfulEdgeAdditionMessage {
            get {
                return ResourceManager.GetString("SuccessfulEdgeAdditionMessage", resourceCulture);
            }
        }
        
        public static string InvalidEdgeCategory {
            get {
                return ResourceManager.GetString("InvalidEdgeCategory", resourceCulture);
            }
        }
        
        public static string InvalidSourceNodeCategory {
            get {
                return ResourceManager.GetString("InvalidSourceNodeCategory", resourceCulture);
            }
        }
        
        public static string InvalidTargetNodeCategory {
            get {
                return ResourceManager.GetString("InvalidTargetNodeCategory", resourceCulture);
            }
        }
        
    }
}
