//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelationshipAnalysis.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RelationshipAnalysis.Test.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cant delete your account!.
        /// </summary>
        internal static string DeleteAccountAccessErrorMessage {
            get {
                return ResourceManager.GetString("DeleteAccountAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen email already exists.
        /// </summary>
        internal static string EmailExistsMessage {
            get {
                return ResourceManager.GetString("EmailExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles cant be empty!.
        /// </summary>
        internal static string EmptyRolesMessage {
            get {
                return ResourceManager.GetString("EmptyRolesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add records failed!.
        /// </summary>
        internal static string FailedAddRecordsMessage {
            get {
                return ResourceManager.GetString("FailedAddRecordsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge category is invalid!.
        /// </summary>
        internal static string InvalidEdgeCategory {
            get {
                return ResourceManager.GetString("InvalidEdgeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered header is invalid.
        /// </summary>
        internal static string InvalidHeaderAttribute {
            get {
                return ResourceManager.GetString("InvalidHeaderAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered node category is invalid.
        /// </summary>
        internal static string InvalidNodeCategory {
            get {
                return ResourceManager.GetString("InvalidNodeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain one digit from 1 to 9, one lowercase letter, one uppercase letter, one special
        ///            character, no space, and it must be 8-16 characters long.
        ///        .
        /// </summary>
        internal static string InvalidPasswordMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles are invalid!.
        /// </summary>
        internal static string InvalidRolesListMessage {
            get {
                return ResourceManager.GetString("InvalidRolesListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Node category is invalid!.
        /// </summary>
        internal static string InvalidSourceNodeCategory {
            get {
                return ResourceManager.GetString("InvalidSourceNodeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Node category is invalid!.
        /// </summary>
        internal static string InvalidTargetNodeCategory {
            get {
                return ResourceManager.GetString("InvalidTargetNodeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed!.
        /// </summary>
        internal static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is required.
        /// </summary>
        internal static string NewPasswordRequired {
            get {
                return ResourceManager.GetString("NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file uploaded!.
        /// </summary>
        internal static string NoFileUploadedMessage {
            get {
                return ResourceManager.GetString("NoFileUploadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name is not unique!.
        /// </summary>
        internal static string NotUniqueCategoryNameErrorMessage {
            get {
                return ResourceManager.GetString("NotUniqueCategoryNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Dto can not be null!.
        /// </summary>
        internal static string NullDtoErrorMessage {
            get {
                return ResourceManager.GetString("NullDtoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is required.
        /// </summary>
        internal static string OldPasswordRequired {
            get {
                return ResourceManager.GetString("OldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required!.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Created Successfuly!.
        /// </summary>
        internal static string SucceddfulCreateUser {
            get {
                return ResourceManager.GetString("SucceddfulCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Created successfylly!.
        /// </summary>
        internal static string SuccessfulCreateCategory {
            get {
                return ResourceManager.GetString("SuccessfulCreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Deleted successfully!.
        /// </summary>
        internal static string SuccessfulDeleteUserMessage {
            get {
                return ResourceManager.GetString("SuccessfulDeleteUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edges added successfully!.
        /// </summary>
        internal static string SuccessfulEdgeAdditionMessage {
            get {
                return ResourceManager.GetString("SuccessfulEdgeAdditionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was successful!.
        /// </summary>
        internal static string SuccessfulLoginMessage {
            get {
                return ResourceManager.GetString("SuccessfulLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout was successful!.
        /// </summary>
        internal static string SuccessfulLogoutMessage {
            get {
                return ResourceManager.GetString("SuccessfulLogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes added successfully.
        /// </summary>
        internal static string SuccessfulNodeAdditionMessage {
            get {
                return ResourceManager.GetString("SuccessfulNodeAdditionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User roles updated successfuly!.
        /// </summary>
        internal static string SuccessfulUpdateRolesMessage {
            get {
                return ResourceManager.GetString("SuccessfulUpdateRolesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated successfully!.
        /// </summary>
        internal static string SuccessfulUpdateUserMessage {
            get {
                return ResourceManager.GetString("SuccessfulUpdateUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two headers have the same title!.
        /// </summary>
        internal static string TwoSameHeadersMessage {
            get {
                return ResourceManager.GetString("TwoSameHeadersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen username already exists.
        /// </summary>
        internal static string UsernameExistsMessage {
            get {
                return ResourceManager.GetString("UsernameExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required!.
        /// </summary>
        internal static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find user!.
        /// </summary>
        internal static string UserNotFoundMessage {
            get {
                return ResourceManager.GetString("UserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is valid!.
        /// </summary>
        internal static string ValidFileMessage {
            get {
                return ResourceManager.GetString("ValidFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered old password is wrong.
        /// </summary>
        internal static string WrongOldPasswordMessage {
            get {
                return ResourceManager.GetString("WrongOldPasswordMessage", resourceCulture);
            }
        }
    }
}
